### ISSUE TITLE
Use of smoothed solutions

### ISSUE THREAD

**Issue by mhardcastle** [cyriltasse/DynSpecMS#2]
Needs to be modified for the current ddf-pipeline to be able to use one big smoothed solution file not in the ms rather than individual files in the ms.

**Comment by cyriltasse** [comment]
wouldn't that be an issue for `ddf-pipeline` instead?

**Comment by mhardcastle** [comment]
Hmm, depends which one of them needs to be changed! Currently ddf-pipeline does pass the wrong name for the sols file; but it's not obvious to me that DynSpecMS can look for one big sols file outside the MS rather than a little one inside the MS, even if it's given the right name.

**Comment by cyriltasse** [comment]
ho - ok I see what you mean... so you want to give a `.npz` instead

**Comment by mhardcastle** [comment]
Well this seems to be fixed, so closing it now.
