### ISSUE TITLE
Huge list of targets

### ISSUE THREAD

**Issue by zhangxiang-planet** [cyriltasse/DynSpecMS#22]
Hi Cyril,

I prepared a target list of ~1700 sources and (unsurprisingly) DynspecMS is running slowly. I've also noticed that the pressure on HPC memory is pretty high. Will it help if I split the list into multiple (e.g. 10) sublists and run DynspecMS sequentially? (Or will that really make a difference?)

The target list includes grid points to cover the entire NenuFAR field, so I set `--noff 0`.

Cheers,
Xiang

**Comment by cyriltasse** [comment]
Yeah I've not had to do that yet, but DynSpecMS should be changed to be able to split the target list by himself. You can either branch it and implement it so that it would do it automatically, or pass it with smaller source lists

**Comment by zhangxiang-planet** [comment]
Thanks. Guess I will pass it with smaller source list and see what happens :-)
