### ISSUE TITLE
Targets list

### ISSUE THREAD

**Issue by mhardcastle** [cyriltasse/DynSpecMS#3]
Is it OK if I modify this to pull the target list out of the surveys database if it's not supplied?

That way we can add targets of interest without having to bother you. I'll just have to ingest the online file into the database.

**Comment by cyriltasse** [comment]
yeah - sounds good... But we'll have to bother you then - or how do I access the target list?

**Comment by mhardcastle** [comment]
I'll put some hooks in the ddf-pipeline surveys_db code to allow sources to be added and removed.
